import React, { useState } from 'react';
import { Input } from '../components/Input/Input';

/** @type { import('@storybook/react-vite').Meta<typeof Input> } */
export default {
  title: 'Meridian/Input',
  component: Input,
  tags: ['autodocs'],
  parameters: {
    docs: {
      description: {
        component:
          'Single-line text field. Provides a label, help text, and an error ' +
          'state. The `<label>` is always linked to the `<input>` via a ' +
          'stable id — either the `id` prop or one generated by `useId`.',
      },
    },
  },
  decorators: [
    (Story) => (
      <div style={{ maxWidth: '400px' }}>
        <Story />
      </div>
    ),
  ],
  argTypes: {
    label: {
      control: 'text',
      description: 'Visible label rendered above the field.',
      table: {
        type: { summary: 'string' },
        defaultValue: { summary: 'undefined' },
      },
    },
    placeholder: {
      control: 'text',
      description: 'Placeholder shown when the field is empty.',
      table: {
        type: { summary: 'string' },
        defaultValue: { summary: 'undefined' },
      },
    },
    helpText: {
      control: 'text',
      description: 'Descriptive copy below the field. Hidden when `errorMessage` is set.',
      table: {
        type: { summary: 'string' },
        defaultValue: { summary: 'undefined' },
      },
    },
    errorMessage: {
      control: 'text',
      description:
        'When non-empty, activates the error state: danger border, ' +
        'error-coloured focus ring, and this message below the field.',
      table: {
        type: { summary: 'string' },
        defaultValue: { summary: 'undefined' },
      },
    },
    disabled: {
      control: 'boolean',
      description: 'Disables the field and applies muted token values.',
      table: {
        type: { summary: 'boolean' },
        defaultValue: { summary: 'false' },
      },
    },
    required: {
      control: 'boolean',
      description: 'Adds `required` to the `<input>` and a `*` indicator to the label.',
      table: {
        type: { summary: 'boolean' },
        defaultValue: { summary: 'false' },
      },
    },
    type: {
      control: { type: 'select' },
      options: ['text', 'email', 'password', 'number', 'search', 'tel', 'url'],
      description: 'Native HTML `type` attribute.',
      table: {
        type: { summary: "'text' | 'email' | 'password' | 'number' | 'search' | 'tel' | 'url'" },
        defaultValue: { summary: 'text' },
      },
    },
    id: {
      control: 'text',
      description:
        'Overrides the auto-generated `id`. Only needed when you must ' +
        'control the id — e.g. for server-rendered forms.',
      table: {
        type: { summary: 'string' },
        defaultValue: { summary: 'auto (useId)' },
      },
    },
    value: {
      control: false,
      description: 'Controlled value. Requires `onChange`.',
      table: {
        type: { summary: 'string' },
        defaultValue: { summary: 'undefined' },
      },
    },
    defaultValue: {
      control: 'text',
      description: 'Uncontrolled default value.',
      table: {
        type: { summary: 'string' },
        defaultValue: { summary: 'undefined' },
      },
    },
    onChange: {
      action: 'changed',
      description: 'Change handler. Required when using controlled `value`.',
      table: {
        type: { summary: '(e: React.ChangeEvent<HTMLInputElement>) => void' },
        defaultValue: { summary: 'undefined' },
      },
    },
    name: {
      control: 'text',
      description: 'Native `name` attribute for form submission.',
      table: {
        type: { summary: 'string' },
        defaultValue: { summary: 'undefined' },
      },
    },
  },
  args: {
    label: 'Label',
    placeholder: 'Placeholder',
    disabled: false,
    required: false,
    type: 'text',
  },
};

/* ==========================================================================
   Single-prop stories
   ========================================================================== */

export const Default = {
  args: { label: 'Email address', placeholder: 'you@example.com', type: 'email' },
};

export const WithHelpText = {
  args: {
    label: 'Username',
    placeholder: 'meridian_user',
    helpText: 'Must be 3–20 characters, letters and numbers only.',
  },
};

export const Error = {
  args: {
    label: 'Email address',
    placeholder: 'you@example.com',
    type: 'email',
    defaultValue: 'not-an-email',
    errorMessage: 'Enter a valid email address.',
  },
  parameters: {
    docs: {
      description: {
        story:
          '`errorMessage` activates the error state. ' +
          'The help text is replaced by the error message and `aria-invalid` is set.',
      },
    },
  },
};

export const Disabled = {
  args: {
    label: 'API key',
    defaultValue: 'sk_live_•••••••••••••••',
    disabled: true,
    helpText: 'Rotate your key in account settings.',
  },
};

export const Required = {
  args: {
    label: 'Full name',
    placeholder: 'Jane Smith',
    required: true,
    helpText: 'As it appears on your government ID.',
  },
};

export const Password = {
  args: {
    label: 'Password',
    placeholder: 'Enter your password',
    type: 'password',
    helpText: 'At least 8 characters.',
  },
};

export const NoLabel = {
  args: {
    placeholder: 'Search…',
    type: 'search',
  },
  parameters: {
    docs: {
      description: {
        story: 'When `label` is omitted, add an `aria-label` via the spread props.',
      },
    },
  },
};

/* ==========================================================================
   All states grid
   ========================================================================== */

export const AllStates = {
  name: 'All States',
  render: () => (
    <div style={{
      fontFamily: 'var(--font-family-sans)',
      padding: 'var(--inset-lg)',
      display: 'flex',
      flexDirection: 'column',
      gap: 'var(--stack-xl)',
      maxWidth: '360px',
    }}>
      <Input
        label="Default"
        placeholder="Resting state"
        helpText="Help text appears here."
      />
      <Input
        label="Required"
        placeholder="Required field"
        required
        helpText="This field is required."
      />
      <Input
        label="Error"
        placeholder="Error state"
        defaultValue="bad@input"
        errorMessage="This field has an error."
      />
      <Input
        label="Disabled"
        placeholder="Disabled field"
        disabled
        helpText="This field is disabled."
      />
    </div>
  ),
  parameters: {
    controls: { disable: true },
    docs: {
      description: { story: 'Default, required, error, and disabled — stacked for side-by-side comparison.' },
    },
  },
};

/* ==========================================================================
   Controlled example
   ========================================================================== */

export const Controlled = {
  render: () => {
    const [value, setValue] = useState('');
    const hasError = value.length > 0 && value.length < 3;
    return (
      <div style={{ maxWidth: '360px', fontFamily: 'var(--font-family-sans)' }}>
        <Input
          label="Display name"
          placeholder="At least 3 characters"
          value={value}
          onChange={(e) => setValue(e.target.value)}
          helpText={`${value.length} characters`}
          errorMessage={hasError ? 'Must be at least 3 characters.' : undefined}
          required
        />
      </div>
    );
  },
  parameters: {
    controls: { disable: true },
    docs: {
      description: { story: 'Controlled input with live character count and inline validation.' },
    },
  },
};
